### ISSUE TITLE
Ejercicio 4

### ISSUE THREAD

**Issue by AlexisVM** [Webimpact-Proyecto-Asuncion/WebImpact#8]
Hola! no encontré su ejercicio 4 en el repo, súbanlo para poder tomarlo en cuenta jeje. Saludos!
https://github.com/Webimpact-Proyecto-Asuncion/WebImpact

**Comment by Royer99** [comment]
Hola Alexis, una mega disculpa por el retraso.
El ejercicio 4 si estaba en el repo pero en una rama aislada.
De cualquier forma ya esta en develop.
Gracias
